run_infer_main_dist.sh: line 15: python: command not found
